services:
  - type: web
    name: badem-menu-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        value: "7954467711:AAH4LCKN_Ag7eY9hJG3D_aTcjgDe81PRY-g"
      - key: CHAT_ID
        value: 5960188505